### ISSUE TITLE
can i use it with laravel

### ISSUE THREAD

**Issue by dark-wind** [adamwojs/php-activiti-api#1]
Thank you for the hard work and share .
it's a very useful project.
+ I can simply use it now,such as add a new user
+ I have run activiti-rest successfully and understand  some basic usage of activiti
+ Can it work with laravel?

I saw the Factory and ObjectSerializer and Service.Why we need "ModelFactoryInterface" and "ObjectSerializerInterface"

**Comment by adamwojs** [comment]
@dark-wind Thank you, I'm glad that is useful for you. 

> Can it work with laravel?

I didn't test it with Laravel but you should be able to do this. This package is just REST API client and nothing more, so is "framework" independent. 

> Why we need "ModelFactoryInterface" and "ObjectSerializerInterface"

From the `Activiti\Client\Service\**` POV: `ModelFactoryInterface` is abstraction of models creation logic from the raw data. `ObjectSerializerInterface` is abstraction in the opposite side.

**Comment by dark-wind** [comment]
Thank you for reply and i'll try it.
If i meet some question,i hope to ask you.
Are you buzying?
